# Generated by Django 6.0.4 on 2026-05-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('buraco', 'Buracos em vias públicas'), ('iluminacao', 'Falha na iluminação pública'), ('lixo', 'Descarte irregular de lixo / entulho'), ('enchente', 'Alagamento / Enchente'), ('outros', 'Outros problemas urbanos')], max_length=50, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Endereço / Localização')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='denuncias/', verbose_name='Fotografia de Evidência')),
                ('anonimo', models.BooleanField(default=False, verbose_name='Denunciar de forma anônima')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('resolvido', 'Resolvido')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta_gestor', models.TextField(blank=True, null=True, verbose_name='Resposta da Administração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
