# Generated by Django 6.0.4 on 2026-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='endereco',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço / Localização'),
        ),
    ]
