# Generated by Django 6.0.5 on 2026-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_denuncia_bairro_denuncia_cep_denuncia_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='zona',
            field=models.CharField(blank=True, choices=[('norte', 'Norte'), ('sul', 'Sul'), ('leste', 'Leste'), ('oeste', 'Oeste'), ('centro', 'Centro'), ('outra', 'Outra/Não informado')], default='outra', max_length=20, verbose_name='Zona/Região'),
        ),
    ]
